version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-node
    ports:
      - "9042:9042"  # Expose the Cassandra port
      - "9160:9160"  # Optional: expose the Thrift port (deprecated in Cassandra 4.0)
    volumes:
      - cassandra_data:/var/lib/cassandra  # Attach a persistent volume for data storage
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCassandraCluster"
      CASSANDRA_NUM_TOKENS: "256"
      CASSANDRA_RPC_ADDRESS: "0.0.0.0"
      CASSANDRA_START_RPC: "true"

volumes:
  cassandra_data:
    driver: local  # Use the local driver for persistence
